# Generated by Django 2.0.2 on 2018-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsUploadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_created=True, verbose_name='время загрузки')),
                ('uploaded_records', models.PositiveIntegerField(default=0, verbose_name='загружено записей')),
                ('status', models.CharField(choices=[('in_progress', 'выполняется'), ('success', 'выполнена'), ('failed', 'ошибка')], default='in_progress', max_length=15, verbose_name='статус')),
            ],
        ),
    ]
