# Generated by Django 2.0.2 on 2018-02-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_currency', models.CharField(max_length=5, verbose_name='первая валюта')),
                ('last_currency', models.CharField(max_length=5, verbose_name='вторая валюта')),
            ],
            options={
                'verbose_name': 'пара валют',
                'verbose_name_plural': 'пары валют',
            },
        ),
        migrations.CreateModel(
            name='StatsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type',
                 models.CharField(blank=True, choices=[('buy', 'покупка'), ('sell', 'продажа')], max_length=5,
                                  null=True, verbose_name='тип')),
                ('exchange', models.CharField(blank=True, choices=[('bittrex', 'BITTREX'), ('binance', 'BINANCE'),
                                                                   ('poloniex', 'POLONIEX')], max_length=10, null=True,
                                              verbose_name='биржа')),
                ('datetime', models.DateTimeField(verbose_name='дата/время')),
                ('price', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='цена 1 монеты при сделке')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='количество продаваемой/покупаемой валюты')),
                ('total', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма продажи/покупки второй валюты')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процент комиссии')),
                ('order', models.BigIntegerField(verbose_name='номер заказа')),
                ('base_total_less_fee', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма транзакции в 1 валюте с учетом комиссии')),
                ('quote_total_less_fee', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма транзакции во 2 валюте с учетом комиссии')),
                ('currency_pair',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.CurrencyPair')),
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистика',
            },
        ),
        migrations.CreateModel(
            name='StatsUploadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=36, verbose_name='ID celery-задачи')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='время загрузки')),
                ('uploaded_records', models.PositiveIntegerField(default=0, verbose_name='загружено записей')),
                ('status', models.CharField(choices=[('in_progress', 'выполняется'), ('success', 'выполнена'), ('failed', 'ошибка')], default='in_progress', max_length=15, verbose_name='статус')),
                ('file',
                 models.FilePathField(allow_folders=True, default=None, recursive=True, verbose_name='путь до файла')),
                ('uploaded_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                   verbose_name='загружено пользователем')),
            ],
            options={
                'verbose_name': 'загрузка статистики',
                'verbose_name_plural': 'загрузка статистики',
            },
        ),
        migrations.CreateModel(
            name='TradeProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='профит')),
                ('date', models.DateField(verbose_name='дата')),
                ('stats_records', models.ManyToManyField(to='stats.StatsRecord', verbose_name='статистические записи')),
            ],
            options={
                'verbose_name': 'профит',
                'verbose_name_plural': 'профиты',
            },
        ),
    ]
