# Generated by Django 2.0.2 on 2018-02-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_currency', models.CharField(max_length=5, verbose_name='первая валюта')),
                ('last_currency', models.CharField(max_length=5, verbose_name='вторая валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'покупка'), ('sell', 'продажа')], max_length=5, verbose_name='тип')),
                ('datetime', models.DateTimeField(verbose_name='дата/время')),
                ('price', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='цена 1 монеты при сделке')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='количество продаваемой/покупаемой валюты')),
                ('total', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма продажи/покупки второй валюты')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процент комиссии')),
                ('order', models.PositiveIntegerField(verbose_name='номер заказа')),
                ('base_total_less_fee', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма транзакции в 1 валюте с учетом комиссии')),
                ('quote_total_less_fee', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма транзакции во 2 валюте с учетом комиссии')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.CurrencyPair')),
            ],
        ),
        migrations.CreateModel(
            name='StatsUploadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_created=True, verbose_name='время загрузки')),
                ('task_id', models.CharField(max_length=36, verbose_name='ID задачи')),
                ('uploaded_records', models.PositiveIntegerField(default=0, verbose_name='загружено записей')),
                ('status', models.CharField(choices=[('in_progress', 'выполняется'), ('success', 'выполнена'), ('failed', 'ошибка')], default='in_progress', max_length=15, verbose_name='статус')),
            ],
        ),
    ]
