# Generated by Django 2.0.2 on 2018-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsuploadevent',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время загрузки'),
        ),
    ]
