# Generated by Django 2.0.2 on 2018-02-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0002_auto_20180226_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeprofit',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_profit',
                                    to='stats.CurrencyPair'),
        ),
    ]
