# Generated by Django 2.0.2 on 2018-02-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180215_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencypair',
            options={'verbose_name': 'пара валют', 'verbose_name_plural': 'пары валют'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'статистика', 'verbose_name_plural': 'статистика'},
        ),
        migrations.AlterModelOptions(
            name='statsuploadevent',
            options={'verbose_name': 'загрузка статистики', 'verbose_name_plural': 'загрузка статистики'},
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='currency',
            new_name='currency_pairs',
        ),
    ]
