# Generated by Django 2.0.2 on 2018-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0004_auto_20180302_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsrecord',
            name='base_total_less_fee',
        ),
        migrations.RemoveField(
            model_name='statsrecord',
            name='order',
        ),
        migrations.RemoveField(
            model_name='statsrecord',
            name='quote_total_less_fee',
        ),
        migrations.AlterField(
            model_name='statsrecord',
            name='fee',
            field=models.DecimalField(decimal_places=8, max_digits=17, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='statsuploadevent',
            name='parse_status',
            field=models.CharField(
                choices=[('in_progress', 'выполняется'), ('error', 'ошибка'), ('success', 'успешно')],
                default='in_progress', max_length=15, verbose_name='статус парсинга'),
        ),
        migrations.AlterField(
            model_name='statsuploadevent',
            name='update_profit_status',
            field=models.CharField(
                choices=[('in_progress', 'выполняется'), ('error', 'ошибка'), ('success', 'успешно')],
                default='in_progress', max_length=15, verbose_name='статус обновления профитов'),
        ),
    ]
