# Generated by Django 2.0.2 on 2018-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0004_auto_20180216_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsuploadevent',
            name='filename',
            field=models.FileField(blank=True, default=None, null=True, upload_to='',
                                   verbose_name='файл'),
        ),
    ]
