# Generated by Django 2.0.2 on 2018-02-18 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0005_auto_20180218_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statsuploadevent',
            old_name='filename',
            new_name='file',
        ),
    ]
