# Generated by Django 2.0.2 on 2018-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0006_auto_20180218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsuploadevent',
            name='file',
            field=models.FilePathField(allow_folders=True, default=None, recursive=True, verbose_name='путь до файла'),
        ),
    ]
