# Generated by Django 2.0.2 on 2018-02-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0007_auto_20180219_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='order',
            field=models.BigIntegerField(verbose_name='номер заказа'),
        ),
    ]
