# Generated by Django 2.0.2 on 2018-02-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0008_auto_20180219_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='type',
            field=models.CharField(blank=True, choices=[('buy', 'покупка'), ('sell', 'продажа')], max_length=5,
                                   null=True, verbose_name='тип'),
        ),
    ]
